<?php
/**
 * OpenAsyncProductApiScrollShortProductByFilterResponseProduct
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * open-async-product-api api
 *
 * open-async-product-api
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * OpenAsyncProductApiScrollShortProductByFilterResponseProduct Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class OpenAsyncProductApiScrollShortProductByFilterResponseProduct implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'open_async_product_apiScrollShortProductByFilterResponseProduct';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'ali_created_at' => '\DateTime',
        'ali_updated_at' => '\DateTime',
        'category_id' => 'string',
        'currency_code' => 'string',
        'delivery_time' => 'string',
        'owner_member_id' => 'string',
        'owner_member_seq' => 'string',
        'freight_template_id' => 'string',
        'group_ids' => 'string[]',
        'main_image_url' => 'string',
        'main_image_urls' => 'string[]',
        'sku' => '\OpenAPI\Client\Model\OpenAsyncProductApiScrollShortProductByFilterResponseSKU[]',
        'subject' => 'string',
        'marketing_images' => '\OpenAPI\Client\Model\ScrollShortProductByFilterResponseMarketingImage[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'ali_created_at' => 'date-time',
        'ali_updated_at' => 'date-time',
        'category_id' => 'int64',
        'currency_code' => null,
        'delivery_time' => 'int64',
        'owner_member_id' => null,
        'owner_member_seq' => 'int64',
        'freight_template_id' => 'int64',
        'group_ids' => 'int64',
        'main_image_url' => null,
        'main_image_urls' => null,
        'sku' => null,
        'subject' => null,
        'marketing_images' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'ali_created_at' => 'ali_created_at',
        'ali_updated_at' => 'ali_updated_at',
        'category_id' => 'category_id',
        'currency_code' => 'currency_code',
        'delivery_time' => 'delivery_time',
        'owner_member_id' => 'owner_member_id',
        'owner_member_seq' => 'owner_member_seq',
        'freight_template_id' => 'freight_template_id',
        'group_ids' => 'group_ids',
        'main_image_url' => 'main_image_url',
        'main_image_urls' => 'main_image_urls',
        'sku' => 'sku',
        'subject' => 'Subject',
        'marketing_images' => 'marketing_images'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'ali_created_at' => 'setAliCreatedAt',
        'ali_updated_at' => 'setAliUpdatedAt',
        'category_id' => 'setCategoryId',
        'currency_code' => 'setCurrencyCode',
        'delivery_time' => 'setDeliveryTime',
        'owner_member_id' => 'setOwnerMemberId',
        'owner_member_seq' => 'setOwnerMemberSeq',
        'freight_template_id' => 'setFreightTemplateId',
        'group_ids' => 'setGroupIds',
        'main_image_url' => 'setMainImageUrl',
        'main_image_urls' => 'setMainImageUrls',
        'sku' => 'setSku',
        'subject' => 'setSubject',
        'marketing_images' => 'setMarketingImages'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'ali_created_at' => 'getAliCreatedAt',
        'ali_updated_at' => 'getAliUpdatedAt',
        'category_id' => 'getCategoryId',
        'currency_code' => 'getCurrencyCode',
        'delivery_time' => 'getDeliveryTime',
        'owner_member_id' => 'getOwnerMemberId',
        'owner_member_seq' => 'getOwnerMemberSeq',
        'freight_template_id' => 'getFreightTemplateId',
        'group_ids' => 'getGroupIds',
        'main_image_url' => 'getMainImageUrl',
        'main_image_urls' => 'getMainImageUrls',
        'sku' => 'getSku',
        'subject' => 'getSubject',
        'marketing_images' => 'getMarketingImages'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['ali_created_at'] = $data['ali_created_at'] ?? null;
        $this->container['ali_updated_at'] = $data['ali_updated_at'] ?? null;
        $this->container['category_id'] = $data['category_id'] ?? null;
        $this->container['currency_code'] = $data['currency_code'] ?? null;
        $this->container['delivery_time'] = $data['delivery_time'] ?? null;
        $this->container['owner_member_id'] = $data['owner_member_id'] ?? null;
        $this->container['owner_member_seq'] = $data['owner_member_seq'] ?? null;
        $this->container['freight_template_id'] = $data['freight_template_id'] ?? null;
        $this->container['group_ids'] = $data['group_ids'] ?? null;
        $this->container['main_image_url'] = $data['main_image_url'] ?? null;
        $this->container['main_image_urls'] = $data['main_image_urls'] ?? null;
        $this->container['sku'] = $data['sku'] ?? null;
        $this->container['subject'] = $data['subject'] ?? null;
        $this->container['marketing_images'] = $data['marketing_images'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id Идентификатор продукта
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets ali_created_at
     *
     * @return \DateTime|null
     */
    public function getAliCreatedAt()
    {
        return $this->container['ali_created_at'];
    }

    /**
     * Sets ali_created_at
     *
     * @param \DateTime|null $ali_created_at Дата создания
     *
     * @return self
     */
    public function setAliCreatedAt($ali_created_at)
    {
        $this->container['ali_created_at'] = $ali_created_at;

        return $this;
    }

    /**
     * Gets ali_updated_at
     *
     * @return \DateTime|null
     */
    public function getAliUpdatedAt()
    {
        return $this->container['ali_updated_at'];
    }

    /**
     * Sets ali_updated_at
     *
     * @param \DateTime|null $ali_updated_at Дата обновления
     *
     * @return self
     */
    public function setAliUpdatedAt($ali_updated_at)
    {
        $this->container['ali_updated_at'] = $ali_updated_at;

        return $this;
    }

    /**
     * Gets category_id
     *
     * @return string|null
     */
    public function getCategoryId()
    {
        return $this->container['category_id'];
    }

    /**
     * Sets category_id
     *
     * @param string|null $category_id Индентификатор категории
     *
     * @return self
     */
    public function setCategoryId($category_id)
    {
        $this->container['category_id'] = $category_id;

        return $this;
    }

    /**
     * Gets currency_code
     *
     * @return string|null
     */
    public function getCurrencyCode()
    {
        return $this->container['currency_code'];
    }

    /**
     * Sets currency_code
     *
     * @param string|null $currency_code Код валюты
     *
     * @return self
     */
    public function setCurrencyCode($currency_code)
    {
        $this->container['currency_code'] = $currency_code;

        return $this;
    }

    /**
     * Gets delivery_time
     *
     * @return string|null
     */
    public function getDeliveryTime()
    {
        return $this->container['delivery_time'];
    }

    /**
     * Sets delivery_time
     *
     * @param string|null $delivery_time Время доставки
     *
     * @return self
     */
    public function setDeliveryTime($delivery_time)
    {
        $this->container['delivery_time'] = $delivery_time;

        return $this;
    }

    /**
     * Gets owner_member_id
     *
     * @return string|null
     */
    public function getOwnerMemberId()
    {
        return $this->container['owner_member_id'];
    }

    /**
     * Sets owner_member_id
     *
     * @param string|null $owner_member_id логин, создавшего продукт
     *
     * @return self
     */
    public function setOwnerMemberId($owner_member_id)
    {
        $this->container['owner_member_id'] = $owner_member_id;

        return $this;
    }

    /**
     * Gets owner_member_seq
     *
     * @return string|null
     */
    public function getOwnerMemberSeq()
    {
        return $this->container['owner_member_seq'];
    }

    /**
     * Sets owner_member_seq
     *
     * @param string|null $owner_member_seq ID, создавшего продукт
     *
     * @return self
     */
    public function setOwnerMemberSeq($owner_member_seq)
    {
        $this->container['owner_member_seq'] = $owner_member_seq;

        return $this;
    }

    /**
     * Gets freight_template_id
     *
     * @return string|null
     */
    public function getFreightTemplateId()
    {
        return $this->container['freight_template_id'];
    }

    /**
     * Sets freight_template_id
     *
     * @param string|null $freight_template_id Идентификатор шаблона доставки, уникален для каждого продавца или шаблона
     *
     * @return self
     */
    public function setFreightTemplateId($freight_template_id)
    {
        $this->container['freight_template_id'] = $freight_template_id;

        return $this;
    }

    /**
     * Gets group_ids
     *
     * @return string[]|null
     */
    public function getGroupIds()
    {
        return $this->container['group_ids'];
    }

    /**
     * Sets group_ids
     *
     * @param string[]|null $group_ids group_ids
     *
     * @return self
     */
    public function setGroupIds($group_ids)
    {
        $this->container['group_ids'] = $group_ids;

        return $this;
    }

    /**
     * Gets main_image_url
     *
     * @return string|null
     */
    public function getMainImageUrl()
    {
        return $this->container['main_image_url'];
    }

    /**
     * Sets main_image_url
     *
     * @param string|null $main_image_url Картинка товара
     *
     * @return self
     */
    public function setMainImageUrl($main_image_url)
    {
        $this->container['main_image_url'] = $main_image_url;

        return $this;
    }

    /**
     * Gets main_image_urls
     *
     * @return string[]|null
     */
    public function getMainImageUrls()
    {
        return $this->container['main_image_urls'];
    }

    /**
     * Sets main_image_urls
     *
     * @param string[]|null $main_image_urls main_image_urls
     *
     * @return self
     */
    public function setMainImageUrls($main_image_urls)
    {
        $this->container['main_image_urls'] = $main_image_urls;

        return $this;
    }

    /**
     * Gets sku
     *
     * @return \OpenAPI\Client\Model\OpenAsyncProductApiScrollShortProductByFilterResponseSKU[]|null
     */
    public function getSku()
    {
        return $this->container['sku'];
    }

    /**
     * Sets sku
     *
     * @param \OpenAPI\Client\Model\OpenAsyncProductApiScrollShortProductByFilterResponseSKU[]|null $sku sku
     *
     * @return self
     */
    public function setSku($sku)
    {
        $this->container['sku'] = $sku;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string|null
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string|null $subject subject
     *
     * @return self
     */
    public function setSubject($subject)
    {
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets marketing_images
     *
     * @return \OpenAPI\Client\Model\ScrollShortProductByFilterResponseMarketingImage[]|null
     */
    public function getMarketingImages()
    {
        return $this->container['marketing_images'];
    }

    /**
     * Sets marketing_images
     *
     * @param \OpenAPI\Client\Model\ScrollShortProductByFilterResponseMarketingImage[]|null $marketing_images Маркетинговые изображения
     *
     * @return self
     */
    public function setMarketingImages($marketing_images)
    {
        $this->container['marketing_images'] = $marketing_images;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


