<?php
/**
 * OpenAsyncProductApiServiceApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * open-async-product-api api
 *
 * open-async-product-api
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OpenAsyncProductApiServiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OpenAsyncProductApiServiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for openAsyncProductApiServiceGetBrandList
     *
     * .
     *
     */
    public function testOpenAsyncProductApiServiceGetBrandList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for openAsyncProductApiServiceGetCategories
     *
     * .
     *
     */
    public function testOpenAsyncProductApiServiceGetCategories()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for openAsyncProductApiServiceGetCategoriesTop
     *
     * .
     *
     */
    public function testOpenAsyncProductApiServiceGetCategoriesTop()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for openAsyncProductApiServiceGetDictionaryByProperty
     *
     * .
     *
     */
    public function testOpenAsyncProductApiServiceGetDictionaryByProperty()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for openAsyncProductApiServiceGetProducts
     *
     * Метод получения продуктов.
     *
     */
    public function testOpenAsyncProductApiServiceGetProducts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for openAsyncProductApiServiceGetTasks
     *
     * Метод получения списка задач на создание/обновление товаров.
     *
     */
    public function testOpenAsyncProductApiServiceGetTasks()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for openAsyncProductApiServiceOfflineProducts
     *
     * Метод перевода продуктов в offline.
     *
     */
    public function testOpenAsyncProductApiServiceOfflineProducts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for openAsyncProductApiServiceOnlineProducts
     *
     * Метод перевода продуктов в online.
     *
     */
    public function testOpenAsyncProductApiServiceOnlineProducts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for openAsyncProductApiServiceProductCreate
     *
     * Метод создания продуктов.
     *
     */
    public function testOpenAsyncProductApiServiceProductCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for openAsyncProductApiServiceProductEdit
     *
     * Полное редактирование продукта.
     *
     */
    public function testOpenAsyncProductApiServiceProductEdit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for openAsyncProductApiServiceProductUpdateField
     *
     * Метод обновления поля продукта.
     *
     */
    public function testOpenAsyncProductApiServiceProductUpdateField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for openAsyncProductApiServiceScrollProductByFilter
     *
     * .
     *
     */
    public function testOpenAsyncProductApiServiceScrollProductByFilter()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for openAsyncProductApiServiceScrollShortProductByFilter
     *
     * .
     *
     */
    public function testOpenAsyncProductApiServiceScrollShortProductByFilter()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for openAsyncProductApiServiceUpdateSkuPrice
     *
     * Метод обновления цены продукта по ску коду.
     *
     */
    public function testOpenAsyncProductApiServiceUpdateSkuPrice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for openAsyncProductApiServiceUpdateSkuStock
     *
     * Метод обновления стока продукта по ску коду.
     *
     */
    public function testOpenAsyncProductApiServiceUpdateSkuStock()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
